function createfigure(xdata1, ydata1, zdata1, ydata2, zdata2, X1, YMatrix1, ZMatrix1)
    %CREATEFIGURE(XDATA1, YDATA1, ZDATA1, YDATA2, ZDATA2, X1, YMATRIX1, ZMATRIX1)
    %  XDATA1:  surface xdata
    %  YDATA1:  surface ydata
    %  ZDATA1:  surface zdata
    %  YDATA2:  surface ydata
    %  ZDATA2:  surface zdata
    %  X1:  vector of x data
    %  YMATRIX1:  matrix of y data
    %  ZMATRIX1:  matrix of z data
    
    %  Auto-generated by MATLAB on 10-Oct-2016 13:40:00
    
    % Create figure
    figure1 = figure('Colormap',[0 0 0]);
    
    % Create axes
    axes1 = axes('Parent',figure1,'PlotBoxAspectRatio',[1 5.4 6.2],'DataAspectRatio',[1 1 1]);
    view(axes1,[90 0]);
    grid(axes1,'on');
    hold(axes1,'on');
    
    % Create mesh
    mesh(xdata1,ydata1,zdata1,'Parent',axes1);
    
    % Create mesh
    mesh(xdata1,ydata2,zdata2,'Parent',axes1);
    
    % Create multiple lines using matrix input to plot3
    plot31 = plot3(X1,YMatrix1,ZMatrix1,'Parent',axes1);
    set(plot31(29),'LineWidth',2);
    set(plot31(30),'LineWidth',2);
    set(plot31(31),'LineWidth',2,'LineStyle','--','Color',[0 0 1]);
    set(plot31(32),'LineWidth',2,'LineStyle','--','Color',[0 0 1]);
    set(plot31(33),'LineWidth',2,'LineStyle','--','Color',[0 0 1]);
    set(plot31(34),'LineWidth',2,'LineStyle','--','Color',[0 0 1]);
    set(plot31(35),'LineWidth',2,'LineStyle','--','Color',[0 0 1]);
    set(plot31(36),'LineWidth',2,'LineStyle','--','Color',[0 0 1]);
    
    % Create xlabel
    xlabel('X');
    
    % Create ylabel
    ylabel('Y');
    
    % Create zlabel
    zlabel('Z');
    
    % Create textbox
    annotation(figure1,'textbox',[0.6838125 0.133817427385892 0.0125416666666667 0.0269709543568465],'String',{'S'},'FitBoxToText','on');
    
    % Create ellipse
    annotation(figure1,'ellipse',[0.678645833333333 0.163900414937759 0.00989583333333333 0.024896265560166],'Color',[1 0 0],'FaceColor',[1 0 0]);
    
    % Create ellipse
    annotation(figure1,'ellipse',[0.329125 0.845435684647303 0.00941666666666668 0.0269709543568464],'FaceColor',[1 0 0]);
    
    % Create textbox
    annotation(figure1,'textbox',[0.3234375 0.873481328357305 0.0161458333333334 0.0290456425970521],'String',{'R'},'FitBoxToText','off');
    
